// <auto-generated />
using System;
using ApiProdutos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiProdutos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiProdutos.Data.Departamento", b =>
                {
                    b.Property<int>("departamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("maximoFuncionarios")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("departamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            departamentoId = 1,
                            maximoFuncionarios = 10,
                            nome = "TI"
                        },
                        new
                        {
                            departamentoId = 2,
                            maximoFuncionarios = 10,
                            nome = "Suporte"
                        });
                });

            modelBuilder.Entity("ApiProdutos.Data.Funcionario", b =>
                {
                    b.Property<int>("funcionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data_entrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("departamento_id")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("funcionarioId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            funcionarioId = 1,
                            data_entrada = new DateTime(2022, 10, 19, 17, 48, 28, 436, DateTimeKind.Local).AddTicks(7909),
                            departamento_id = 1,
                            nome = "Filipe"
                        },
                        new
                        {
                            funcionarioId = 2,
                            data_entrada = new DateTime(2022, 10, 19, 17, 48, 28, 437, DateTimeKind.Local).AddTicks(4188),
                            departamento_id = 2,
                            nome = "Fernando"
                        });
                });

            modelBuilder.Entity("ApiProdutos.Data.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estoque = 10,
                            Nome = "Fichario",
                            Preco = 10.75m
                        },
                        new
                        {
                            Id = 2,
                            Estoque = 8,
                            Nome = "Bolsinha",
                            Preco = 30.50m
                        },
                        new
                        {
                            Id = 3,
                            Estoque = 5,
                            Nome = "Lapiseira",
                            Preco = 100.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
